language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.03
    - android-28
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    -.+

notifications:
  email:
      on_failure: change

script:
  - ./gradlew clean check
  - ./gradlew build
