language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-28
    - build-tools-28.0.2
    - extra-android-m2repository

notifications:
  email:
      on_failure: change

script:
  - ./gradlew clean check
  - ./gradlew build
